<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shail-Dell-PC" failures="1" tests="1" name="TestRuner.TestRunner" time="13.330" errors="0" timestamp="2023-03-11T14:56:17 GMT" skipped="0">
  <testcase classname="TestRuner.TestRunner" name="runScenario" time="13.330">
    <failure message="expected [https://smartbazaar.co.com/] but found [Smartbazaar – World of Asian Foods]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://smartbazaar.co.com/] but found [Smartbazaar – World of Asian Foods]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.TestCase.user_verifies_the_title_of_the_application(TestCase.java:29)
at ✽.User verifies the title of the application(file:///C:/Users/psnar/IdeaProjects/org.SamrBazar.com/src/test/resources/Feature/TestCase.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- TestRuner.TestRunner -->
